# Project information
site_name: Josiah's Code Snippets
site_url: https://jojoduquartier.github.io/
site_description: Sharing Python code snippets and Notebooks.

# Repository
# repo_name: jojoduquartier/jojoduquartier.github.io
# repo_url: https://github.com/jojoduquartier/jojoduquartier.github.io
# edit_uri: ""

# Copyright
copyright: ©Copyright 2020 - Josiah Hounyo

nav:
  - Home: index.md
  - Snippets:
    - Try/Catch Decorator: snippets/logging_decorator.md
    - Close DB Connections: snippets/close_db_connections.md
    - Organize DB Credentials: snippets/organize_db_connections.md
    - Same Function Name - Different Data Types: snippets/use_single_dispatch.md
    - Pandas Dataframe to Database: snippets/dataframe_to_database.md
  - Fun Projects:
    - Select Projects: projects/projects.md
  - Python Packages:
    - Packages: packages/python_packages.md
theme:
  name: material
  # custom_dir: 'cinder'
extra:
  disqus: jojoduquartier
markdown_extensions:
  - meta
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
